var geometries = [{
    r: 1,
    x: 75,
    y: 40,
    z: -25,
    url: "https://en.wikipedia.org/wiki/Social_justice_warrior",
    title: "SJWs (Social Justice Warriors)",
    content: "Trigger warning please",
    imageName: "SJWs.png",
    planet_texture: "SJWs.png",
    subreddit: "r/gamerghazi, r/shitredditsays",
    subreddit_comments: 2509686,
    ur_text: ""
 },{
    r: 1,
    x: 60,
    y: 50,
    z: -10,
    url: "https://en.wikipedia.org/wiki/Animal_rights_movement",
    title: "Animal Rights Activists",
    content: "Animal Rights = Human Rights",
    imageName: "Animal Rights Activists.jpg",
    planet_texture: "Animal Rights Activists.jpg",
    subreddit: "r/vegan, r/AnimalRights, r/vegancirclejerk",
    subreddit_comments: 3620867,
    ur_text: "Singer, Peter (1975) Animal Liberation: A New Ethics for our Treatment of Animals"
 },{
    r: 1,
    x: 67,
    y: -20,
    z: -25,
    url: "https://en.wikipedia.org/wiki/Black_Lives_Matter",
    title: "Black Lives Matter",
    content: "Hand's Up, Don't Shoot ",
    imageName: "Black Lives Matter.png",
    planet_texture: "Black Lives Matter.png",
    subreddit: "r/BlackLivesMatter",
    subreddit_comments: 5543,
    ur_text: "Fanon, Frantz (1952) Black Skin, White Masks"
 },{
    r: 1,
    x: 80,
    y: 30,
    z: -5,
    url: "https://en.wikipedia.org/wiki/Me_Too_movement",
    title: "#MeToo",
    content: "Time's Up",
    imageName: "MeToo.jpg",
    planet_texture: "MeToo.jpg",
    subreddit: "r/meToo",
    subreddit_comments: 4290,
    ur_text: "Davis, Angela (1971) If They Come in the Morning: Voices of Resistance"
 },{
    r: 1,
    x: 40,
    y: 40,
    z: -35,
    url: "https://en.wikipedia.org/wiki/Fourth-wave_feminism",
    title: "4th Wave Feminist",
    content: "No feminism without intersectionalism ",
    imageName: "4th Wave Feminist.jpg",
    planet_texture: "4th Wave Feminist.jpg",
    subreddit: "r/feminism, r/TrollXChromosomes, r/TwoXChromosomes",
    subreddit_comments: 14513588,
    ur_text: ""
 },{
    r: 1,
    x: 5,
    y: -30,
    z: -50,
    url: "https://en.wikipedia.org/wiki/Angela_Davis",
    title: "PoC Radical Feminist  ",
    content: "Angela Davis",
    imageName: "PoC Radical Feminist.jpg",
    planet_texture: "PoC Radical Feminist.jpg",
    subreddit: "-",
    subreddit_comments: 0,
    ur_text: ""
 },{
    r: 1,
    x: 75,
    y: 5,
    z: -15,
    url: "https://en.wikipedia.org/wiki/LGBT",
    title: "LGBT",
    content: "All love is equal",
    imageName: "LGBT.png",
    planet_texture: "LGBT.png",
    subreddit: "r/lgbt, r/ainbow, r/actuallesbians, r/gay, r/bisexuality",
    subreddit_comments: 4626360,
    ur_text: ""
 },{
    r: 1,
    x: 30,
    y: 10,
    z: -30,
    url: "https://en.wikipedia.org/wiki/Social_construction_of_gender",
    title: "Gender Deconstructionists",
    content: "Gender is a social construct",
    imageName: "Gender Deconstructionists.png",
    planet_texture: "Gender Deconstructionists.jpg",
    subreddit: "r/transgender, r/traaaaaaannnnnnnnnns",
    subreddit_comments: 1799594,
    ur_text: "Butler, Judith (1990) Gender Trouble: Feminism and the Subversion of Identity"
 },{
    r: 1,
    x: 30,
    y: 60,
    z: -10,
    url: "https://en.wikipedia.org/wiki/Radical_feminism",
    title: "Gender-Critical Feminists",
    content: "Gender is not a social construct",
    imageName: "Gender-Critical Feminists.png",
    planet_texture: "Gender-Critical Feminists.png",
    subreddit: "r/GenderCritical/, r/RadicalFeminism",
    subreddit_comments: 940298,
    ur_text: ""
 },{
    r: 1,
    x: -40,
    y: -75,
    z: -55,
    url: "https://en.wikipedia.org/wiki/Queer_anarchism",
    title: "Queer anarchists",
    content: "Gender is state oppression",
    imageName: "Queer anarchists.png",
    planet_texture: "Queer anarchists.png",
    subreddit: "r/radicalqueers, r/anarchism",
    subreddit_comments: 1428873,
    ur_text: ""
 },{
    r: 1,
    x: 50,
    y: -50,
    z: -80,
    url: "https://en.wikipedia.org/wiki/Neo-Marxism",
    title: "Neo-Marxists",
    content: "Workers of the world, re-unite!",
    imageName: "Neo-Marxists.png",
    planet_texture: "Neo-Marxists.png",
    subreddit: "r/socialism, r/marxism, r/communism, r/communism101",
    subreddit_comments: 1867297,
    ur_text: ""
 },{
    r: 1,
    x: 75,
    y: 0,
    z: -55,
    url: "https://en.wikipedia.org/wiki/Antifa_(United_States)",
    title: "Antifa",
    content: "NAZIS RAUS",
    imageName: "Antifa.jpg",
    planet_texture: "Antifa.jpg",
    subreddit: "r/AntifascistsofReddit/, r/fuckthealtright",
    subreddit_comments: 569609,
    ur_text: ""
 },{
    r: 1,
    x: 50,
    y: -15,
    z: -20,
    url: "https://en.wikipedia.org/wiki/Occupy_movement",
    title: "Occupy",
    content: "We are the 99%",
    imageName: "Occupy.jpg",
    planet_texture: "Occupy.jpg",
    subreddit: "r/occupywallstreet/, r/Occupy/",
    subreddit_comments: 411543,
    ur_text: "Hardt, Michael and Antonio Negri (2000) Empire"
 },{
    r: 1,
    x: -20,
    y: 45,
    z: -45,
    url: "https://en.wikipedia.org/wiki/Chapo_Trap_House",
    title: "Dirtbag Left",
    content: "\"That's praxis\" (alternate: posting is praxis)",
    imageName: "Dirtbag Left.jpg",
    planet_texture: "Dirtbag Left.jpg",
    subreddit: "r/DirtbagLeft/, r/chapotraphouse",
    subreddit_comments: 5109317,
    ur_text: "Chapo Trap House (2018) The Chapo Guide to Revolution: A Manifesto Against Logic, Facts and Reason"
 },{
    r: 1,
    x: 20,
    y: 45,
    z: -18,
    url: "https://en.wikipedia.org/wiki/Democratic_Socialists_of_America",
    title: "DSA (Democratic Socialists of America)",
    content: "Bernie would have won ",
    imageName: "DSA.jpg",
    planet_texture: "DSA.jpg",
    subreddit: "r/demsocialists/, r/dsa/, r/DemocraticSocialism/, r/SandersforPresident",
    subreddit_comments: 5165609,
    ur_text: "Sanders, Bernie (2017) Bernie Sanders Guide to Political Revolution",
 },{
    r: 1,
    x: 90,
    y: 75,
    z: -2,
    url: "https://en.wikipedia.org/wiki/Democratic_Party_(United_States)",
    title: "Establishment Left",
    content: "Still with her.",
    imageName: "Establishment Left.jpg",
    planet_texture: "Establishment Left.jpg",
    subreddit: "r/progressive",
    subreddit_comments: 276602,
    ur_text: ""
 },{
    r: 1,
    x: -70,
    y: 90,
    z: -65,
    url: "https://en.wikipedia.org/wiki/Communist_Party_of_Great_Britain#Tankie",
    title: "Tankies",
    content: "Stalin did nothing wrong",
    imageName: "Tankies.png",
    planet_texture: "Tankies.png",
    subreddit: "r/JordanPeterson",
    subreddit_comments: 1207335,
    ur_text: ""
 },{
    r: 1,
    x: 95,
    y: 70,
    z: 10,
    url: "https://twitter.com/BillGates/status/1086662632587907072?ref_src=twsrc%5Etfw",
    title: "Neo-Panglossians",
    content: "I've got a good feeling about this!",
    imageName: "Neo-Panglossians.jpg",
    planet_texture: "Neo-Panglossians.jpg",
    subreddit: "r/Philanthropy",
    subreddit_comments: 922,
    ur_text: ""
 },{
    r: 1,
    x: 0,
    y: -5,
    z: 40,
    title: "New Atheists",
    url: "https://en.wikipedia.org/wiki/New_Atheism",
    content: "In this moment, I am euphoric. Not because of any phony god's blessing. But because, I am enlightened by my intelligencey intelligence",
    imageName: "New Atheists.jpg",
    planet_texture: "New Atheists.jpg",
    subreddit: "r/atheism, r/SamHarris",
    subreddit_comments: 22240465,
    ur_text: "Dawkins, Richard (2006) The God Delusion"
 },{
    r: 1,
    x: -35,
    y: 0,
    z: 30,
    url: "https://en.wikipedia.org/wiki/Epistemology#Street",
    title: "Street Epistemologists",
    content: "Socrates.",
    imageName: "Street Epistemologists.jpg",
    planet_texture: "Street Epistemologists.jpg",
    subreddit: "r/StreetEpistemology/",
    subreddit_comments: 2936,
    ur_text: ""
 },{
    r: 1,
    x: -15,
    y: 15,
    z: 20,
    url: "https://en.wikipedia.org/wiki/Rationalism",
    title: "Rationalist Diaspora",
    content: "What would Bayes do?",
    imageName: "Rationalist Diaspora.png",
    planet_texture: "Rationalist Diaspora.png",
    subreddit: "r/RationalistDiaspora/, /r/slatestarcodex/, r/hpmor, r/themotte",
    subreddit_comments: 809076,
    ur_text: "Yudkowsky, Eliezer - Less Wrong Sequences"
 },{
    r: 1,
    x: -30,
    y: -50,
    z: 20,
    url: "https://en.wikipedia.org/wiki/Integral_theory_(Ken_Wilber)",
    title: "Integral Theorists",
    content: "It's all connected, man",
    imageName: "Integral Theorists.jpg",
    planet_texture: "Integral Theorists.jpg",
    subreddit: "r/Integral/",
    subreddit_comments: 896,
    ur_text: "Wilber, Ken (1970)  - The Spectrum of Consciousness",
 },{
    r: 1,
    x: 25,
    y: 85,
    z: 50,
    url: "https://en.wikipedia.org/wiki/Jordan_Peterson",
    title: "Sorters",
    content: "🐸 Lobsters are hierarchical!",
    imageName: "Sorters.jpg",
    planet_texture: "Sorters.jpg",
    subreddit: "r/jordanpeterson",
    subreddit_comments: 1207335,
    ur_text: "Peterson, Jordan - 12 Rules for Life"
 },{
    r: 1,
    x: 12,
    y: 75,
    z: 45,
    url: "https://en.wikipedia.org/wiki/Intellectual_dark_web",
    title: "Intellectual Dark Web",
    content: "Debate me",
    imageName: "Intellectual Dark Web.png",
    planet_texture: "Intellectual Dark Web.png",
    subreddit: "r/IntellectualDarkWeb/, r/DaveRubin, r/JoeRogan",
    subreddit_comments: 1726760,
    ur_text: ""
 },{
    r: 1,
    x: -45,
    y: 95,
    z: 65,
    url: "https://oilab.eu/deus-vult-tracing-the-many-misuses-of-a-meme/",
    title: "Crusaders",
    content: "Deus vult",
    imageName: "Crusaders.png",
    planet_texture: "Crusaders.png",
    subreddit: "r/CrusaderKings, r/eu4",
    subreddit_comments: 4024991,
    ur_text: "The Bible"
 },{
    r: 1,
    x: -20,
    y: -40,
    z: -35,
    url: "https://en.wikipedia.org/wiki/Modern_Paganism",
    title: "Neo-Paganists",
    content: "Witchcraft, with more crystals and less brooms ",
    imageName: "Neo-Paganists.jpg",
    planet_texture: "Neo-Paganists.jpg",
    subreddit: "r/paganism",
    subreddit_comments: 10370,
    ur_text: ""
 },{
    r: 1,
    x: -5,
    y: 0,
    z: 65,
    url: "https://en.wikipedia.org/wiki/Heathenry_(new_religious_movement)",
    title: "Odinism",
    content: "I am a white supremacist",
    imageName: "Odinism.jpg",
    planet_texture: "Odinism.jpg",
    subreddit: "r/heathenry",
    subreddit_comments: 12823,
    ur_text: "The Poetic Edda"
 },{
    r: 1,
    x: 95,
    y: 85,
    z: 60,
    url: "https://en.wikipedia.org/wiki/Christian_right",
    title: "Christian Right",
    content: "What would Jesus do?",
    imageName: "Christian Right.jpg",
    planet_texture: "Christian Right.jpg",
    subreddit: "r/ConservativeChristian/",
    subreddit_comments: 543,
    ur_text: "The Bible (King James Version)"
 },{
    r: 1,
    x: 55,
    y: -20,
    z: 85,
    url: "https://en.wikipedia.org/wiki/Libertarianism",
    title: "Libertarians",
    content: "Anarcho-capitalism for the 1%",
    imageName: "Libertarians.png",
    planet_texture: "Libertarians.png",
    subreddit: "r/libertarian, r/neoliberal, r/GoldandBlack",
    subreddit_comments: 10610215,
    ur_text: ""
 },{
    r: 1,
    x: 87,
    y: 55,
    z: 55,
    url: "https://en.wikipedia.org/wiki/Republican_Party_(United_States)",
    title: "Establishment Right",
    content: "Please clap",
    imageName: "Establishment Right.png",
    planet_texture: "Establishment Right.png",
    subreddit: "r/conservative/",
    subreddit_comments: 3248519,
    ur_text: ""
 },{
    r: 1,
    x: 82,
    y: -5,
    z: 65,
    url: "https://en.wikipedia.org/wiki/Tea_Party_movement",
    title: "Tea Party",
    content: "more like oBUMMER",
    imageName: "Tea Party.png",
    planet_texture: "Tea Party.png",
    subreddit: "r/republican",
    subreddit_comments: 427950,
    ur_text: ""
 },{
    r: 1,
    x: -25,
    y: 75,
    z: 60,
    url: "https://en.wikipedia.org/wiki/Political_positions_of_Donald_Trump",
    title: "Trumpists",
    content: "Make America Great Again",
    imageName: "Trumpists.jpg",
    planet_texture: "Trumpists.jpg",
    subreddit: "r/The_Donald",
    subreddit_comments: 40397013,
    ur_text: "Trump, Donald - The Art of the Deal"
 },{
    r: 1,
    x: -55,
    y: -60,
    z: 75,
    title: "InfoWarriors",
    url: "https://en.wikipedia.org/wiki/InfoWars",
    content: "Everything I don't like is a false flag - alternatively: \"they're putting chemicals in the water that turn the friggin' frogs gay.\"e friggin' frogs gay.",
    imageName: "InfoWarriors.png",
    planet_texture: "InfoWarriors.png",
    subreddit: "r/conspiracy",
    subreddit_comments: 10931457,
    ur_text: "Alex Jones\' YouTube channel"
 },{
    r: 1,
    x: -65,
    y: 85,
    z: 75,
    url: "https://en.wikipedia.org/wiki/QAnon",
    title: "QAnoners",
    content: "Where we go one we go all ",
    imageName: "QAnoners.jpg",
    planet_texture: "QAnoners.jpg",
    subreddit: "r/Qanon, r/thegreatawakening",
    subreddit_comments: 354,
    ur_text: "/pol/"
 },{
    r: 1,
    x: 45,
    y: 0,
    z: 50,
    url: "https://en.wikipedia.org/wiki/Alt-lite",
    title: "Alt-Lite",
    content: "Triggered, libtard? ",
    imageName: "Alt-Lite.jpg",
    planet_texture: "Alt-Lite.jpg",
    subreddit: "r/TheNewRight, r/ShitLiberalsSay, r/SocialJusticeinAction",
    subreddit_comments: 538813,
    ur_text: ""
 },{
    r: 1,
    x: 10,
    y: 40,
    z: 70,
    url: "https://en.wikipedia.org/wiki/Alt-right",
    title: "Alt-Right",
    content: "Dress well and hate things",
    imageName: "Alt-Right.jpg",
    planet_texture: "Alt-Right.jpg",
    subreddit: "r/AltRightChristian",
    subreddit_comments: 6146,
    ur_text: ""
 },{
    r: 1,
    x: 90,
    y: 87,
    z: 80,
    url: "https://en.wikipedia.org/wiki/Neo-Nazism",
    title: "Modern Neo-Nazis",
    content: "We must secure the existence of our people and a future for white children",
    imageName: "Modern Neo-Nazis.png",
    planet_texture: "Modern Neo-Nazis.png",
    subreddit: "r/nationalsocialism",
    subreddit_comments: 13068,
    ur_text: ""
 },{
    r: 1,
    x: -80,
    y: 90,
    z: 83,
    url: "https://en.wikipedia.org/wiki/Gamergate_controversy",
    title: "Neoreactionaries",
    content: "\"I no longer believe that freedom and democracy are compatible\"?",
    imageName: "Neoreactionaries.jpg",
    planet_texture: "Neoreactionaries.jpg",
    subreddit: "r/DarkEnlightenment",
    subreddit_comments: 52392,
    ur_text: ""
 },{
    r: 1,
    x: -30,
    y: 10,
    z: 50,
    url: "https://en.wikipedia.org/wiki/Gamergate_controversy",
    title: "Gamergaters",
    content: "Get your politics out of my video games",
    imageName: "Gamergaters.jpg",
    planet_texture: "Gamergaters.jpg",
    subreddit: "r/KotakuinAction",
    subreddit_comments: 6297465,
    ur_text: ""
 },{
    r: 1,
    x: 20,
    y: 25,
    z: 25,
    url: "https://en.wikipedia.org/wiki/Men%27s_rights_movement",
    title: "MRA (Mens Right Advocates)",
    content: "Men have rights too! ",
    imageName: "MRA.jpg",
    planet_texture: "MRA.jpg",
    subreddit: "r/MensRights",
    subreddit_comments: 4288049,
    ur_text: ""
 },{
    r: 1,
    x: -30,
    y: -30,
    z: 35,
    url: "https://en.wikipedia.org/wiki/Manosphere",
    title: "The Red Pill",
    content: "Down the misogynist rabbit hole",
    imageName: "The Red Pill.png",
    planet_texture: "The Red Pill.png",
    subreddit: "r/TheRedPill, r/RedPillWomen, r/AskTRP",
    subreddit_comments: 4776465,
    ur_text: ""
 },{
    r: 1,
    x: -10,
    y: -45,
    z: 20,
    url: "https://en.wikipedia.org/wiki/Men_Going_Their_Own_Way",
    title: "MGTOW (Men Going Their Own Way)",
    content: "Lesbian separatism, but for men (but no homo)",
    imageName: "MGTOW.png",
    planet_texture: "MGTOW.png",
    subreddit: "r/MGTOW",
    subreddit_comments: 3560404,
    ur_text: ""
 },{
    r: 1,
    x: -60,
    y: -40,
    z: 40,
    url: "https://en.wikipedia.org/wiki/Incel",
    title: "Incels",
    content: "Forever alone",
    imageName: "Incels.png",
    planet_texture: "Incels.png",
    subreddit: "r/Braincels, r/incelswithouthate, r/incels",
    subreddit_comments: 3956999,
    ur_text: ""
 },{
    r: 1,
    x: -75,
    y: -85,
    z: -90,
    url: "https://en.wikipedia.org/wiki/Anarcho-communism",
    title: "Anarcho-communism",
    content: "Whats mine is yours",
    imageName: "Anarcho-communism.png",
    planet_texture: "Anarcho-communism.png",
    subreddit: "r/anarchocommunism",
    subreddit_comments: 7026,
    ur_text: ""
 },{
    r: 1,
    x: -90,
    y: -95,
    z: 0,
    url: "https://en.wikipedia.org/wiki/Anarcho-primitivism",
    title: "Anarcho-primitivism",
    content: "Luddism for anarchists",
    imageName: "Anarcho-primitivism.jpg",
    planet_texture: "Anarcho-primitivism.jpg",
    subreddit: "/r/anarcho_primitivism",
    subreddit_comments: 5018,
    ur_text: ""
 },{
    r: 1,
    x: -60,
    y: -70,
    z: 0,
    url: "https://en.wikipedia.org/wiki/Anarchist_schools_of_thought#Anarcho-transhumanism",
    title: "Anarcho-transhumanism",
    content: "I want to be a computer (if we were all computers, we'd finally be equal)",
    imageName: "Anarcho-transhumanism.jpg",
    planet_texture: "Anarcho-transhumanism.jpg",
    subreddit: "r/anarchotranshumanist",
    subreddit_comments: 1114,
    ur_text: ""
 },{
    r: 1,
    x: -55,
    y: -85,
    z: 90,
    url: "https://en.wikipedia.org/wiki/Anarcho-capitalism",
    title: "Anarcho-capitalism",
    content: "\"I was beat up by left anarchists in Greece. (self.Anarcho_Capitalism)\"",
    imageName: "Anarcho-capitalism.jpg",
    planet_texture: "Anarcho-capitalism.jpg",
    subreddit: "r/AnarchoCapitalism",
    subreddit_comments: 3389,
    ur_text: ""
 },{
    r: 1,
    x: -15,
    y: -75,
    z: -70,
    url: "https://en.wikipedia.org/wiki/Anarcho-syndicalism",
    title: "Anarcho-syndicalist ",
    content: "Workers of the world, unite! (but not too much)",
    imageName: "Anarcho-syndicalist .png",
    planet_texture: "Anarcho-syndicalist .png",
    subreddit: "r/anarchosyndicalism",
    subreddit_comments: 156,
    ur_text: ""
 },{
    r: 1,
    x: -62,
    y: -65,
    z: 83,
    url: "https://en.wikipedia.org/wiki/Agorism",
    title: "Agorists",
    content: "What if everything was bought and sold like drugs?",
    imageName: "Agorists.jpg",
    planet_texture: "Agorists.jpg",
    subreddit: "r/Agorism",
    subreddit_comments: 7713,
    ur_text: ""
 },{
    r: 1,
    x: -42,
    y: -55,
    z: -75,
    url: "https://en.wikipedia.org/wiki/Anarcho-pacifism",
    title: "Anarcho-pacifists ",
    content: "uwu wevowution pwease? (don't hit me)",
    imageName: "Anarcho-pacifists .jpg",
    planet_texture: "Anarcho-pacifists .jpg",
    subreddit: "r/AnarchoPacifism",
    subreddit_comments: 884,
    ur_text: ""
 },{
    r: 1,
    x: -10,
    y: -80,
    z: 5,
    url: "https://en.wikipedia.org/wiki/Mutualism_(movement)",
    title: "Mutualists (also anarcho-mututalists) ",
    content: "It's free real estate",
    imageName: "Mutualists (also anarcho-mututalists) .jpg",
    planet_texture: "Mutualists (also anarcho-mututalists) .jpg",
    subreddit: "r/mutualism",
    subreddit_comments: 4983,
    ur_text: ""
 },{
    r: 1,
    x: -30,
    y: -75,
    z: -75,
    url: "https://en.wikipedia.org/wiki/Anarcha-feminism",
    title: "Anarcha-feminists",
    content: "Patriarchy dies with the state ",
    imageName: "Anarcha-feminists.jpg",
    planet_texture: "Anarcha-feminists.jpg",
    subreddit: "r/anarchafeminism",
    subreddit_comments: 2011,
    ur_text: ""
 },{
    r: 1,
    x: -77,
    y: -90,
    z: 67,
    url: "https://en.wikipedia.org/wiki/Egoism",
    title: "Egoism",
    content: "Everything I don't like is a spook. ",
    imageName: "Egoism.png",
    planet_texture: "Egoism.png",
    subreddit: "/r/egoism",
    subreddit_comments: 0,
    ur_text: ""
 },{
    r: 1,
    x: -85,
    y: -90,
    z: 99,
    url: "https://en.wikipedia.org/wiki/Anarcho-individualism",
    title: "Anarcho-individualism",
    content: "Revolution? More like self-evolution.",
    imageName: "Anarcho-individualism.jpg",
    planet_texture: "Anarcho-individualism.jpg",
    subreddit: "r/IndividualAnarchism",
    subreddit_comments: 1112,
    ur_text: ""
 },{
    r: 1,
    x: -60,
    y: 0,
    z: 0,
    url: "https://jacobitemag.com/2017/05/25/a-quick-and-dirty-introduction-to-accelerationism/",
    title: "Unconditional Accellerationism",
    content: "The only way out is through",
    imageName: "Unconditional Accellerationism.jpg",
    planet_texture: "Unconditional Accellerationism.jpg",
    subreddit: "r/accelerationism",
    subreddit_comments: 72,
    ur_text: ""
 },{
    r: 1,
    x: -20,
    y: 25,
    z: -65,
    url: "https://www.laboriacuboniks.net/",
    title: "Xenofemism/G-Acc",
    content: "If nature is unjust, change nature.",
    imageName: "XenofemismG-Acc.png",
    planet_texture: "XenofemismG-Acc.png",
    subreddit: "/r/xenofeminism",
    subreddit_comments: 0,
    ur_text: ""
 },{
    r: 1,
    x: -45,
    y: 35,
    z: -85,
    url: "http://criticallegalthinking.com/2013/05/14/accelerate-manifesto-for-an-accelerationist-politics/",
    title: "Left Accelerationism",
    content: "Fully Automated Luxury Communism",
    imageName: "Left Accelerationism.jpg",
    planet_texture: "Left Accelerationism.jpg",
    subreddit: "r/accelerationism, r/falc",
    subreddit_comments: 73,
    ur_text: ""
    }
 ]